<template>
    <!-- Indice 영역 (나중에 작업 예정) -->
    <div class="qlik-indice">
        <IndiceCard
            v-for="(indice, idx) in indices"
            :title = indice.title
            :updateDate = indice.updateDate 
            :value= indice.value 
            :prevValue= indice.prevValue
            :unit= indice.unit
            :basis= indice.basis
            :appId= indice.appId
        />
    </div>
  
    <!-- Grid 영역 (QlikCard 재사용) -->
    <div class="qlik-grid">
      <QlikCard
        v-for="(card, idx) in cards"
        :key="idx"
        :title="card.title"
        :icons="card.icons"
        :filters="card.filters"
        :appId="appId"
        :objId="card.objId"
        :domId="card.domId"
        :updateDate="card.updateDate"
      />
    </div>
  </template>
  
  <script setup>
  import { onMounted } from "vue";
  import QlikCard from "./QlikCard.vue";
  import IndiceCard from './IndiceCard.vue'
  
  const appId = "52e79fa9-bf89-4da3-8a6f-82fe6aa01e5a";
  
  const cards = [
    { title: "Title 1", objId: "NaKQwM", domId: "QV01", updateDate: "2025-08-27" },
    { title: "Title 2", objId: "fzrxtjq", domId: "QV02", updateDate: "2025-08-27" },
    { title: "Title 3", objId: "nvqpV", domId: "QV03", updateDate: "2025-08-27" },
    { title: "Title 4", objId: "qZPdytp", domId: "QV04", updateDate: "2025-08-27" },
    { title: "Title 5", objId: "kTkyjf", domId: "QV05", updateDate: "2025-08-27" },
    { title: "Title 6", objId: "PgmMHr", domId: "QV06", updateDate: "2025-08-27" }
  ];

  const indices = [
    { 
        title: "[ECOS] 일 평균 CO2 배출량 (Ton)", 
        updateDate: "2025-08-29 02:00", 
        unit: "Ton",
        value : 9200,
        prevValue : 9160,
        basis: "day",
        appId: appId
    },
    { 
        title: "[ECOS] 일 평균 EII", 
        updateDate: "2025-08-29 02:00", 
        unit: "", 
        value : 80.48,
        prevValue : 79.85,
        basis: "month",
        appId: appId
    },
    { 
        title: "[OA] All Unit (Forecast) (%)", 
        updateDate: "2025-08-29 02:00", 
        unit: "%", 
        value : 96.51,
        prevValue : 96.52,
        basis: "day",
        appId: appId
    },
    { 
        title: "[PU] Process Utilzation (%)", 
        updateDate: "2025-08-29 02:00", 
        unit: "%",
        value : 86.78,
        basis: "year",
        appId: appId
    },
  ];
  
  //ticket 획득
  const ticket_api = 'http://localhost:8123/qlik/ticket'
  const vp_prefix = '/ticket'

  async function issueTicket() {
    const payload = {
      userId: 'user01',
      userDirectory: 'DEV-QLIK'
    }

    const resp = await fetch(ticket_api, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    })

    if(!resp.ok) throw new Error('Ticket Fail')
    const json = await resp.json();
    return json.Ticket;
  }

  async function establishSession(ticket){
    const xrfkey = 'somerandomstring'
    const res = await fetch(
      `${vp_prefix}/qrs/about?xrfkey=${xrfkey}&qlikTicket=${ticket}`,
      {
        method: 'GET',
        headers: { 'X-Qlik-XrfKey': xrfkey},
        credentials: 'include'
      }
    )
    if(!res.ok) throw new Error('about fail')
  }
  function injectLink(href) {
    return new Promise((resolve, reject) => {
      if (document.querySelector(`link[data-qlik-src="${href}"]`)) return resolve()
      const el = document.createElement('link')
      el.rel = 'stylesheet'
      el.href = href
      el.dataset.qlikSrc = href
      el.onload = resolve
      el.onerror = () => reject(new Error(`CSS 로드 실패: ${href}`))
      document.head.appendChild(el)
    })
  }

  function injectScript(src) {
    return new Promise((resolve, reject) => {
      if (document.querySelector(`script[data-qlik-src="${src}"]`)) return resolve()
      const el = document.createElement('script')
      el.src = src
      el.defer = true
      el.dataset.qlikSrc = src
      el.onload = resolve
      el.onerror = () => reject(new Error(`JS 로드 실패: ${src}`))
      document.head.appendChild(el)
    })
  }

  async function loadQlikResources() {
    await injectLink(`${vp_prefix}/resources/autogenerated/qlik-styles.css`)
    await injectScript(`${vp_prefix}/resources/assets/external/requirejs/require.js`)
  }

  onMounted(async () => {
    //const ticket = await issueTicket()          // 1) 티켓 발급
    //await establishSession(ticket)              // 2) 세션 수립
    //await loadQlikResources()                   // 3) CSS/JS 주입

    // requirejs(["js/qlik"], (qlik) => {
    //   const app = qlik.openApp(appId, {
    //     host: "dev.jsct.site",
    //     prefix: "/ticket/",
    //     isSecure: true,
    //     port: 443
    //   });
  
    //   // Indice 오브젝트 로딩 (추후 커스터마이징)
    //   app.getObject("QI01", "HDuUjmn");
    //   app.getObject("QI02", "HDuUjmn");
    //   app.getObject("QI03", "HDuUjmn");
    //   app.getObject("QI04", "HDuUjmn");
    // });

    
  });
  </script>
  
  <style scoped>
  .qlik-indice{
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 16px;
    padding: 16px 20px 0 20px;
    }
  .qlik-indice-card {
    background: #fff;
    border-radius: 12px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.15);
    padding: 10px;
    min-height: 100px;
  }
  .qlik-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-auto-rows: 400px;
    gap: 10px;
    padding: 20px;
  }
  </style>
  